PowerGrids.Electrical.Machines.SynchronousMachine4Windings {{NAME}}(
    H = {{INERTIA}},
    PStart = {{PGEN}},
    QStart = {{QGEN}},
    SNom = {{SNOM}},
    Tpd0 = {{TPDO}},
    Tppd0 = {{TPPDO}},
    Tppq0 = {{TPPQO}}, 
    Tpq0 = {{TPQO}}, 
    UNom = {{VNOM}}, 
    UPhaseStart = {{VANGLE}}, 
    UStart = {{VSTART}}, 
    portVariablesPhases = true, 
    raPu = {{RAPU}}, 
    xdPu = {{XDPU}}, 
    xlPu = {{XLPU}}, 
    xpdPu = {{XPDPU}}, 
    xppdPu = {{XPPDPU}}, 
    xppqPu = {{XPPQPU}}, 
    xpqPu = {{XPQPU}}, 
    xqPu = {{XQPU}}) 
annotation (Placement(visible = {{VISIBLE}}, transformation(extent = {{TRANS_EXTENT_POINTS}}, rotation = {{ROTATION}}, origin = {{ORIGIN_POINT}})));
