variables:
  DOCKER_TAG_DEV: ${CI_COMMIT_REF_NAME}
  DOCKER_IMAGE_DEV: cim2mod-dev

stages:
  - prepare
  - build
  - test

docker:
  stage: prepare
  script:
    - docker build -t ${DOCKER_IMAGE_DEV}:${DOCKER_TAG_DEV} .
    - docker images
  tags:
    - shell

build: 
  stage: test
  image: ${DOCKER_IMAGE_DEV}:${DOCKER_TAG_DEV}
  tags:
    - docker
  before_script:
    - git clone --recursive https://${GITLAB_USER}:${GITLAB_TOKEN}@git.rwth-aachen.de/acs/core/cim/cimpp/libcimpp.git/ libcimpp/
    - mkdir -p build && cd build
    - cmake ..
    - make -j8
  script:
    - cd test/
    - ./testFiles.py


