variables:
  DOCKER_TAG_DEV: ${CI_COMMIT_REF_NAME}
  DOCKER_IMAGE_DEV: cim2mod-dev

stages:
  - prepare
  - test
# build the docker img in which we want to test. normally we want a dockerfile with all dependencies which we just include
docker:
  stage: prepare
  script:
    - docker build -t ${DOCKER_IMAGE_DEV}:${DOCKER_TAG_DEV} .
    - docker images
  tags:
    - shell
# clone libcimpp in our projekt. compile and run the tests.
test: 
  stage: test
  image: ${DOCKER_IMAGE_DEV}:${DOCKER_TAG_DEV}
  tags:
    - docker
  before_script:
    - rm -rf libcimpp/
    - git clone --recursive https://${GITLAB_USER}:${GITLAB_TOKEN}@git.rwth-aachen.de/acs/core/cim/cimpp/libcimpp.git/ libcimpp/
    - mkdir -p build && cd build
    - cmake .. -DUSE_CIM_VERSION:STRING=IEC61970_16v29a_SINERGIEN
    - make -j8

only:
    - master
    - release

  script:
    - cd ../test/
    - ./testFiles.py


