FROM ubuntu:latest

RUN apt-get update

# Add openmodelica respoitory
RUN apt-get install -y wget lsb-release gnupg
RUN for deb in deb deb-src; do echo "$deb http://build.openmodelica.org/apt `lsb_release -cs` stable"; done | tee /etc/apt/sources.list.d/openmodelica.list
RUN wget -q http://build.openmodelica.org/apt/openmodelica.asc -O- | apt-key add -

# Install openmodelica
RUN apt-get update
RUN apt-get install -y openmodelica

# Install git
RUN apt-get install -y git

